
[general]
	#
	# Should TFC forcefully skip the 'Experimental World Generation' warning screen when creating or loading a world?
	# Note: this also speeds up loading a world by about 2x.
	ignoreExperimentalWorldGenWarning = true
	#
	# Enables a series of additional debugging tooltips, displayed information, and logging.
	enableDebug = false

[display]
	#
	# Replace the vanilla hunger bar with a TFC one.
	enableHungerBar = true
	#
	# Replaces the vanilla health bar with a TFC one.
	enableHealthBar = true
	#
	# Adds a TFC thirst bar over the hotbar.
	enableThirstBar = true
	#
	# Allows the vanilla XP bar to render.
	enableExperienceBar = true
	#
	# Enables squids inking your screen.
	enableInkSplatter = true
	#
	# Enables 'screen particles' that spawn on the screen when knapping rocks.
	enableScreenParticles = true
	#
	# Enables the vanilla tutorial toasts that appear during gameplay. These can be difficult to make disappear in modded environments, so they are disabled by default.
	enableVanillaTutorialToasts = false
	#
	# Adjusts the position where potion effects render in the X direction. By default, this moves them to the right of the inventory tabs. Negative values shift them to the left.
	#Range: -128 ~ 128
	effectHorizontalAdjustment = 20
	#
	# Health display format. This affects what number is displayed on top of the tfc-style health bar
	#   TFC - e.g. 750 / 1000
	#   VANILLA - e.g. 15.0 / 20.0
	#   TFC_CURRENT - e.g. 750
	#   VANILLA_CURRENT - e.g. 15.0
	#Allowed Values: TFC, VANILLA, TFC_CURRENT, VANILLA_CURRENT
	healthDisplayStyle = "TFC"
	#
	# Food expiry tooltip display style. This affects what information is shown on the food item stack tooltips.
	#   NONE - Shows nothing. Maximum mystery!
	#   EXPIRY - e.g. 'Expires on June 3, 05:00
	#   TIME_LEFT - e.g. 'Expires in about 3 day(s)
	#   BOTH - Shows both of the above, e.g. Expires on June 3, 05:00 (in about 3 day(s)).
	#Allowed Values: NONE, EXPIRY, TIME_LEFT, BOTH
	foodExpiryTooltipStyle = "BOTH"
	#
	# The overlay color to indicate rotten foods. Default = 0x88CC33
	#Range: 0 ~ 16777215
	foodExpiryOverlayColor = 8965171
	#
	# The style to display all heat tooltips in.
	#   COLOR = Approximate, color based tooltips (like Very Hot**, Brilliant White)
	#   CELSIUS = Exact degrees Celsius
	#   FAHRENHEIT = Exact degrees Fahrenheit
	#   KELVIN = Exact Kelvin
	#   RANKINE = Exact degrees Rankine
	#Allowed Values: COLOR, CELSIUS, FAHRENHEIT, RANKINE, KELVIN
	heatTooltipStyle = "COLOR"
	#
	# The style to display all external (i.e. climate) temperature in.
	#   COLOR = Approximate, color based tooltips (like Very Hot**, Brilliant White)
	#   CELSIUS = Exact degrees Celsius
	#   FAHRENHEIT = Exact degrees Fahrenheit
	#   KELVIN = Exact Kelvin
	#   RANKINE = Exact degrees Rankine
	#Allowed Values: COLOR, CELSIUS, FAHRENHEIT, RANKINE, KELVIN
	climateTooltipStyle = "CELSIUS"
	#
	# The style to display all time delta / duration tooltips in.
	#   DAYS = Display values larger than a month as a number of days, i.e. '105 day(s)'
	#   DAYS_MONTHS = Display values larger than a year as a number of months and days, i.e. '13 month(s), 1 day(s)'
	#   DAYS_MONTHS_YEARS = Display values as normal, i.e. '1 year(s), 1 month(s), 1 day(s)'
	#Allowed Values: DAYS_MONTHS_YEARS, DAYS_MONTHS, DAYS
	timeDeltaTooltipStyle = "DAYS_MONTHS_YEARS"
	#
	# The style to display HUD elements when the XP bar is disabled.
	#   HOVER = Display all elements in their default positions
	#   BUMP = Move elements closer to the hotbar; when fishing or riding a jumping entity, other elements move to their default positions
	#   LEFT_HOTBAR = Move elements closer to the hotbar; when fishing or riding a jumping entity, those elements will appear as a vertical bar between the hotbar and offhand slot
	#Allowed Values: HOVER, BUMP, LEFT_HOTBAR
	disabledExperienceBarStyle = "HOVER"
	#
	# If prospect information should appear in the space above the hotbar (the actionbar). False will put them in the chat window.
	sendProspectResultsToActionbar = true
	#
	# If hoe overlays (for hydration, nutrition, or temperature, shown when hovering over a plant or farmland while holding a hoe), should only be shown when the shift key is held down.
	showHoeOverlaysOnlyWhenShifting = false
	#
	# If true, mods like Jade that add info when hovering on a block will add the hoe's overlay info to the tooltip, even when not holding a hoe.
	showHoeOverlaysInInfoMods = true
	#
	# If familiarity is displayed as a percent rather than a heart
	displayFamiliarityAsPercent = false
	#
	# If, when hovering over an item in the inventory, or looking at a block in the world that has a linked page in the guide book, should it display a tooltip along with allowing you to hold Ctrl/Cmd to quickly navigate to that page in the book.
	showGuideBookLinksAlways = true
	#
	# If a button linking to the TFC Field Guide should be added to the inventory, climate, nutrition, and calendar screens?
	showGuideBookTabInInventory = true
	#
	# For items like bundles, their contents inside will be rendered using Bundle Technology to show their items.
	displayItemContentsAsImages = true
	#
	# If true, for items that are hot, they will show a bar on the item like a durability bar
	displayItemHeatBars = true
	#
	# If true, particles specifically for wind will appear.
	enableWindParticles = true

[compatibility]
	#
	# Registers additional models into forge's special model registry.
	# For Pack Makers: this is needed if you want your custom item models to render when used for panning (if they are not already used somewhere else and added automatically in that case)
	additionalSpecialModels = []

